const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
const GET_BY_ID = 'GET_BY_ID';
const CREATE_PRODUCT = 'CREATE_PRODUCT';
const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
const DELETE_PRODUCT = 'DELETE_PRODUCT';
const GET_CATEGORIES = 'GET_CATEGORIES';

export {
    GET_ALL_PRODUCTS,
    SEARCH_PRODUCTS,
    GET_BY_ID,
    CREATE_PRODUCT,
    UPDATE_PRODUCT,
    DELETE_PRODUCT,
    GET_CATEGORIES
}
