const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
const GET_BY_ID = 'GET_BY_ID';
const CREATE_PRODUCT = 'CREATE_PRODUCT';
const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
const DELETE_PRODUCT = 'DELETE_PRODUCT';

export {
    GET_ALL_PRODUCTS,
    GET_BY_ID,
    CREATE_PRODUCT,
    UPDATE_PRODUCT,
    DELETE_PRODUCT
}
